on: [push, pull_request]
name: "CI"

defaults:
  run:
    shell: bash

jobs:
  build-rust-version:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - "1.83"
          - "stable"
          - "beta"
          - "nightly"
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update && sudo apt install -y nasm
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: rustup override set ${{ matrix.toolchain }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo build

  build-os:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: ConorMacBride/install-package@v1
        with:
          brew: nasm
          apt: nasm
          choco: nasm
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@1.83
      - uses: Swatinem/rust-cache@v2
      - run: cargo build

  lint:
    runs-on: ubuntu-26.04
    steps:
      - run: sudo apt update && sudo apt install -y nasm
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - run: rustup component add clippy
      - uses: Swatinem/rust-cache@v1
      - run: cargo clippy

  test:
    runs-on: ubuntu-26.04
    steps:
      - run: sudo apt update && sudo apt install -y nasm
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@1.83
      - uses: Swatinem/rust-cache@v2
      - run: cargo test

  examples:
    runs-on: ubuntu-26.04
    steps:
      - run: sudo apt update && sudo apt install -y nasm
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@1.83
      - uses: Swatinem/rust-cache@v2
      - run: cargo run --example compressor
      - run: cargo run --example decompressor
      - run: cargo run --example downscale
      - run: cargo run --example image --features image
